# Chart Releaser configuration
owner: albal
git-repo: nginx-helm
charts-repo-url: https://albal.github.io/nginx-helm
index-path: index.yaml
package-path: .cr-release-packages
generate-release-notes: true